# Code generated by Gemini to convert the mainframe text file (txt) to json. 

import json

def main():
    modern_records = []

    with open("mainframe_data.txt", "r") as file:
        for line in file:
            name = line[0:10].strip()
            emp_id = line[10:15].strip()
            balance = line[15:22].strip()

            formattad_balance = float(balance) / 100

            record = {
                "name": name,
                "id": int(emp_id),
                "balance": formattad_balance
            }

            modern_records.append(record)

    with open("modernized_data.json", "w") as json_file:
        json.dump(modern_records, json_file, indent = 4)

    print("Done with converting mainframe_data to modernized_data.json")


if __name__ == "__main__":
    main()



