# Python code to generate test data with 100s of records. 
# Name , Emp_Id and account Balance

# code generated by google gemini and copied by Karthikeyan

import random

def main():
    names = ["SMITH", "JONES", "BROWN", "GARCIA", "MILLER", "DAVIS", "MARTINEZ", "WILSON"]
    
    with open("mainframe_data.txt", "w") as f:
        for i in range(100):
            # 1. Generate a random name and pad it to 10 characters
            name = random.choice(names).ljust(10)
            
            # 2. Generate a 5-digit ID (e.g., 00101)
            emp_id = str(i + 1).zfill(5)
            
            # 3. Generate a random balance (e.g., 0005000 for $50.00)
            # We multiply by 100 to simulate the "implied decimal"
            balance_num = random.randint(1000, 99999)
            balance = str(balance_num).zfill(7)
            
            # Write the fixed-width line
            f.write(f"{name}{emp_id}{balance}\n")
            
    print("Successfully generated 100 legacy records in mainframe_data.txt")

if __name__ == "__main__":
    main()